### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by arcanumursi** [arcanumursi/APP2000-applikasjonsutvikling-21h-22v#16]
Profil bilde bug. Legge inn overskrift og fikse det samme som i offline

**Comment by aass90** [comment]
Profilbilde fungerer. Overskrift er på plass på begge sider (online / offline)
Rettet på lenker.
Endret på tittel, styling slik at det harmonerer bedre med resten.

**Comment by arcanumursi** [comment]
Online contact ser litt rar ut hos meg. Contact form ligger langt ned på siden (nesten under footer)
